const data = {
  products: [
    {
      name: 'Free Shirts',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      contInStock: 20,
      description: 'A nice shirt',
    },
    {
      name: 'Free Shirts',
      category: 'Shirts',
      image: 'images/shirt2.jpg',
      price: 90,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      contInStock: 20,
      description: 'A nice shirt',
    },
    {
      name: 'Free Shirts',
      category: 'Shirts',
      image: 'images/shirt1.jpg',
      price: 50,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 10,
      contInStock: 20,
      description: 'A nice shirt',
    },
    {
      name: 'Free Shirts',
      category: 'Pants',
      image: 'images/pants1.jpg',
      price: 80,
      brand: 'Puma',
      rating: 5,
      numReviews: 10,
      contInStock: 20,
      description: 'A nice shirt',
    },
    {
      name: 'Free Shirts',
      category: 'Pants',
      image: 'images/pants2.jpg',
      price: 60,
      brand: 'NewBalace',
      rating: 4.5,
      numReviews: 10,
      contInStock: 20,
      description: 'A nice shirt',
    },
    {
      name: 'Free Shirts',
      category: 'Pants',
      image: 'images/pants3.jpg',
      price: 110,
      brand: 'ATA',
      rating: 5,
      numReviews: 10,
      contInStock: 20,
      description: 'A nice shirt',
    },
  ],
};

export default data;
